name: Build and Deploy to EC2
on:
  push:
    branches:
      - main
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: 457865735160
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t your-registry/your-image:latest .
      
      - name: Copy Docker image to EC2
        run: |
          scp -i key.pem your-registry/your-image:latest ec2-user@184.73.95.168:~

      - name: SSH into EC2 and deploy
        run: |
          ssh -i key.pem ec2-user@184.73.95.168 'docker load -i ~/your-image_latest.tar'
          ssh -i key.pem ec2-user@184.73.95.168 'docker run -d -p 80:3000 your-registry/your-image:latest'
